# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# lintr
r_github_packages:
  - jimhester/lintr
after_success:
  - Rscript -e 'lintr::lint_package()'
